### PR TITLE
added some changes regarding the HIVE requirement

### PR DESCRIPTION
**Pull request by Ngalstyan4**
I realised that the installation package has HIVE installation as a prerequisite.
However, as the bigdata trend goes  more to InMemory Computing, many are not going to use Hive.
Moreover, Apache spark SQL now supports almost everything done by spark so I don't see any reason why Hive should be prerequisite for Zeppelin notebook.
SO I updated the installation script so that there is no Hive requirement.
I am posting here my initial commit and if you agree that Hive is indeed not a required component, I will improve the changes and update the documentation!.

I look forward to your response to push further changes!

yours, 

Narek

### CODE REVIEW

**Comment by abajwa-hw** [comment]
Hi Narek
Thanks for your PR. I agree that it's better practice to only configure hive interpreter if hive is installed on the cluster. I guess same goes for Phoenix. Do you want to include all your proposed changes before merging?

Thanks
Ali

**Comment by Ngalstyan4** [comment]
Ok, I can do that

I will try to finish all the changes and update the documentation over the weekend and then you can merge it

**Comment by Ngalstyan4** [comment]
Seems to be done regarding the Hive part!
I deleted my installation and reinstalled the notebook using my forked repo and it went without any errors.
As about Phoenix, I could not find the existence of which parameter should be checked in Hadoop configs before creating the interpretor so I left it unchanged

**Comment by abajwa-hw** [comment]
Looks good...thanks!

**Pull request merged**
